name: Deploy
on:
  release:
    types: [ released, prereleased ]

jobs:
  variables:
    name: Set Variables
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-variables.outputs.version }}
      channel: ${{ steps.set-variables.outputs.channel }}
    steps:
      - name: Set Variables
        id: set-variables
        run: |
          if [ ${{ github.event.action }} == 'prereleased' ]; then
            echo "::set-output name=CHANNEL::Insiders"
            echo "::set-output name=VERSION::${{ github.event.release.tag_name }}-insiders"
          else
            echo "::set-output name=CHANNEL::Public"
            echo "::set-output name=VERSION::${{ github.event.release.tag_name }}"
          fi

  build:
    name: Build
    needs: variables
    runs-on: ${{ matrix.os.runner }}
    strategy:
      matrix:
        os:
          - { runner: windows-latest, runtime: win-x64 }
          - { runner: ubuntu-latest, runtime: ubuntu.20.04-x64 }
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
          source-url: https://nuget.pkg.github.com/vignette-project/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}

      - name: Build
        run: |
          dotnet publish Vignette.Desktop/Vignette.Desktop.csproj -c Release -o ./release -r ${{ matrix.os.runtime }} --self-contained true -p:Version=${{ needs.variables.outputs.version }}
          7z a -tzip Vignette.${{ needs.variables.outputs.version }}-${{ matrix.os.runtime }}.zip release/*

      - name: Stage Artifact for AppCenter
        uses: actions/upload-artifact@v2
        with:
          name: ${{ needs.variables.outputs.version }}-${{ matrix.os.runtime }}
          path: ${{ github.workspace }}/Vignette.${{ needs.variables.outputs.version }}-${{ matrix.os.runtime }}.zip
          retention-days: 1

  deploy:
     name: Deploy
     needs: [ variables, build ]
     runs-on: ubuntu-latest
     strategy:
        matrix:
           runtime: ['win-x64', 'linux-x64']
     steps:
       - name: Download Artifact
         uses: actions/download-artifact@v2
         with:
            name: ${{ needs.variables.outputs.version }}-${{ matrix.runtime }}
            path: ${{ github.workspace }}
            
       - name: Upload Build
         uses: ncipollo/release-action@v1
         if: ${{ github.event.action == 'released' }}
         with:
           artifacts: "Vignette.${{ needs.variables.outputs.version }}-${{ matrix.runtime }}.zip"
           allowUpdates: true
           tag: ${{ github.event.release.tag_name }}
           

       - name: Upload Build (Insider)
         if: ${{ github.event.action == 'prereleased' }}
         uses: wzieba/AppCenter-Github-Action@v1.3.2
         with:
           appName: vignette/Vignette-AB1
           token: ${{ secrets.VS_APP_CENTER_TOKEN }}
           group: ${{ needs.variables.outputs.channel }}
           buildVersion: ${{ needs.variables.outputs.version }}-${{ matrix.runtime }}
           file: Vignette.${{ needs.variables.outputs.version }}-${{ matrix.runtime }}.zip
           notifyTesters: true


  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [ variables, deploy ]
    steps:
      - name: Notify Insiders
        uses: Ilshidur/action-discord@master
        with:
          args: Heads up <@&871618277258960897>! `${{ needs.variables.outputs.version }}` is now available! Visit the App Center to get your build.
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_INS }}
        if: ${{ github.event.action == 'prereleased' }}

      - name: Notify Public
        uses: Ilshidur/action-discord@master
        with:
          args: |
           Heads up @everyone! `${{ needs.variables.outputs.version }}` is now available! 
           https://github.com/vignetteapp/vignette/releases/tag/${{ github.event.release.tag_name }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_REL }}
        if: ${{ github.event.action == 'released' }}
